trigger:


pool:
vmImage: "ubuntu-latest"


variables:
TF_VERSION: "1.5.7"


steps:
- checkout: self
persistCredentials: true


- task: Bash@3
name: install_terraform
inputs:
targetType: 'inline'
script: |
set -e
TFV=${TF_VERSION}
wget https://releases.hashicorp.com/terraform/${TFV}/terraform_${TFV}_linux_amd64.zip -O /tmp/terraform.zip
unzip -o /tmp/terraform.zip -d /usr/local/bin
terraform -version


- task: Bash@3
name: az_login
env:
ARM_CLIENT_ID: $(ARM_CLIENT_ID)
ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
ARM_TENANT_ID: $(ARM_TENANT_ID)
ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
inputs:
targetType: 'inline'
script: |
set -e
echo "Logging into Azure..."
az login --service-principal -u "$ARM_CLIENT_ID" -p "$ARM_CLIENT_SECRET" --tenant "$ARM_TENANT_ID"
az account set --subscription "$ARM_SUBSCRIPTION_ID"


- task: Bash@3
name: tf_init
env:
ARM_CLIENT_ID: $(ARM_CLIENT_ID)
ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
ARM_TENANT_ID: $(ARM_TENANT_ID)
ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
inputs:
targetType: 'inline'
script: |
set -e
terraform init -input=false


- task: Bash@3
name: tf_plan
env:
ARM_CLIENT_ID: $(ARM_CLIENT_ID)
ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
ARM_TENANT_ID: $(ARM_TENANT_ID)
ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
TF_VAR_admin_ssh_key: $(VM_ADMIN_SSH_PUB)
inputs:
targetType: 'inline'
script: |
set -e
terraform plan -out=tfplan -input=false


- task: Bash@3
name: tf_apply
env:
ARM_CLIENT_ID: $(ARM_CLIENT_ID)
ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
ARM_TENANT_ID: $(ARM_TENANT_ID)
ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
TF_VAR_admin_ssh_key: $(VM_ADMIN_SSH_PUB)
inputs:
targetType: 'inline'
script: |
set -e
terraform apply -auto-approve tfplan